- hosts: prod
  vars:
    monitoring_user: nobody
    monitoring_group: nogroup
    monitoring_uid: 65534
    monitoring_path: "{{ third_party_packages_path }}/monitoring"

    prometheus_path: "{{ monitoring_path }}/prometheus"
    prometheus_etc_path: "{{ prometheus_path }}/etc"
    prometheus_port: 9090
    prometheus_external_port: 9090

    docker_subnet: 172.16.238.0/24
    docker_gateway: 172.16.238.1
    docker_exporter_external_port: 9323

    node_exporter_path: "{{ third_party_packages_path }}/node_exporter"
    node_exporter_external_port: 9100

    grafana_path: "{{ monitoring_path }}/grafana"
    grafana_etc_path: "{{ grafana_path }}/etc"
    grafana_provisioning_path: "{{ grafana_etc_path }}/provisioning"
    grafana_lib_path: "{{ grafana_path }}/lib"
    grafana_log_path: "{{ grafana_path }}/log"
    grafana_external_port: 3000

    alertmanager_path: "{{ monitoring_path }}/alertamanager"
    alertmanager_etc_path: "{{ alertmanager_path }}/etc"
    alertmanager_port: 9093
  tasks:
    - include_role:
        name: docker
        tasks_from: "{{ item }}"
        apply:
          tags: docker
      with_items:
        - docker
        - docker_compose
        - metrics
      tags: docker

    - include_role:
        name: monitoring
        apply:
          tags: server
      tags: server

    - include_role:
        name: node_exporter
        tasks_from: run
        apply:
          tags: node
      tags: node
