- hosts: prod
  vars:
    monitoring_user: nobody
    monitoring_group: nogroup
    monitoring_uid: 65534
    monitoring_path: "{{ third_party_packages_path }}/monitoring"

    prometheus_path: "{{ monitoring_path }}/prometheus"
    prometheus_etc_path: "{{ prometheus_path }}/etc"
    prometheus_port: 9090
    prometheus_external_port: 9090

    docker_subnet: 172.16.238.0/24
    docker_gateway: 172.16.238.1
    docker_exporter_external_port: 9323

    node_exporter_path: "{{ third_party_packages_path }}/node_exporter"
    node_exporter_external_port: 9100

    grafana_path: "{{ monitoring_path }}/grafana"
    grafana_etc_path: "{{ grafana_path }}/etc"
    grafana_provisioning_path: "{{ grafana_etc_path }}/provisioning"
    grafana_lib_path: "{{ grafana_path }}/lib"
    grafana_log_path: "{{ grafana_path }}/log"
    grafana_external_port: 3000

    alertmanager_path: "{{ monitoring_path }}/alertamanager"
    alertmanager_port: 9093
  tasks:
    - include_role:
        name: docker
        tasks_from: "{{ item }}"
        apply:
          tags: docker
      with_items:
        - docker
        - docker_compose
        - metrics
      tags: docker

    - include_role:
        name: node_exporter
        tasks_from: run
        apply:
          tags: node
      tags: node #!

    - name: run monitoring server
      block:
        - name: create user
          ansible.builtin.user:
            name: "{{ monitoring_user }}"
            uid: "{{ monitoring_uid }}"
            group: "{{ monitoring_group }}"
            home: "{{ monitoring_path }}"
            shell: "/bin/bash"
        - name: create directory structure
          ansible.builtin.file:
            path: "{{ item }}"
            state: directory
            owner: "{{ monitoring_user }}"
            group: "{{ monitoring_group }}"
          with_items:
            - "{{ monitoring_path }}"

            - "{{ prometheus_path }}"
            - "{{ prometheus_etc_path }}"

            - "{{ grafana_path }}"
            - "{{ grafana_etc_path }}"
            - "{{ grafana_provisioning_path }}"
            - "{{ grafana_provisioning_path }}/datasources"
            - "{{ grafana_provisioning_path }}/dashboards"
            - "{{ grafana_lib_path }}"
            - "{{ grafana_log_path }}"
        - name: template prometheus configs
          ansible.builtin.template:
            src: "{{ item.src }}"
            dest: "{{ item.dest }}"
            owner: "{{ monitoring_user }}"
            group: "{{ monitoring_group }}"
          with_items:
            - {src: "prometheus/prometheus.yml", dest: "{{ prometheus_etc_path }}"}
            - {src: "prometheus/alerts.yml", dest: "{{ prometheus_etc_path }}"}
        - name: generate password for grafana
          set_fact:
            grafana_admin_password: "{{ lookup('password', '/dev/null chars=ascii_lowercase,ascii_uppercase,digits length=8') }}"
        - name: template grafana configs
          ansible.builtin.template:
            src: "{{ item.src }}"
            dest: "{{ item.dest }}"
            owner: "{{ monitoring_user }}"
            group: "{{ monitoring_group }}"
          with_items:
            - {src: "grafana/grafana.ini", dest: "{{ grafana_etc_path }}"}
            - {src: "grafana/provisioning/prometheus.yaml", dest: "{{ grafana_provisioning_path }}/datasources"}
            - {src: "grafana/provisioning/dashboards.yaml", dest: "{{ grafana_provisioning_path }}/dashboards"}
        - name: sync dashboards
          ansible.posix.synchronize:
            src: "grafana/dashboards/"
            dest: "{{ grafana_lib_path }}/dashboards"
            recursive: true
        - name: set permissions
          ansible.builtin.file:
            path: "{{ grafana_lib_path }}/dashboards"
            state: directory
            owner: "{{ monitoring_user }}"
            group: "{{ monitoring_group }}"
        # - name: template alertmanager configs
        #   ansible.builtin.template:
        #     src: "{{ item.src }}"
        #     dest: "{{ item.dest }}"
        #     owner: "{{ monitoring_user }}"
        #     group: "{{ monitoring_group }}"
        #   with_items:
        #     - {src: "alertmanager/alertmanager.yml", dest: "{{ alertmanager_etc_path }}"}
        #     - {src: "alertmanager/alerts.yml", dest: "{{ alertmanager_etc_path }}"}
        - name: template docker-compose.yml
          ansible.builtin.template:
            src: docker-compose.yml
            dest: "{{ monitoring_path }}/"
            owner: "{{ monitoring_user }}"
            group: "{{ monitoring_group }}"
        - name: down server
          community.docker.docker_compose:
            project_src: "{{ monitoring_path }}"
            state: absent
        - name: up server
          community.docker.docker_compose:
            project_src: "{{ monitoring_path }}"
        - ansible.builtin.debug:
            msg:
              - "Grafana URL: http://{{ hostvars['server'].ansible_host }}:{{ grafana_external_port }}"
              - "Grafana password for 'admin' user: {{ grafana_admin_password }}"
              - ""
              - "Prometheus URL: http://{{ hostvars['server'].ansible_host }}:{{ prometheus_external_port }}"
      tags: server
